### ISSUE TITLE
[FEEDBACK] - Part B Security Reference Architecture

### ISSUE THREAD

**Issue by ruoguarch** [tewhatuora/api-standards#107]
### Summary

can we also add PEP and PDP from security policy perspective

### Which area of the standards does this apply to?

- [ ] Part A - API Concepts
- [X] Part B - API Security
- [ ] Part C - API Design and Development
- [ ] Part D - FHIR
- [ ] Community guidelines

**Comment by felix-tewhatuora** [comment]
Hi @ruoguarch, good call out regarding Policy Enforcement Points (PEP) and Policy Decision Points (PDP) regarding APIs. 

Ideally, PEP should be implemented at all ingress points. However, it might be a challenge to provide concrete architectural advice given the varied ways one can implement an API (microservices, BFFs, serverless functions, etc.), things get even more complex when services are surfaced via API gateways.

What we can do is to privide a high-level guiding principle on where policy enforcement should take place.

I'll be closing this issue for now, will make necessary adjustments to the document. Thank you so much for the feedback. :)
