### ISSUE TITLE
[FEEDBACK] - FHIR API Design Principles

### ISSUE THREAD

**Issue by cflemeister** [tewhatuora/api-standards#125]
### Summary

Im wondering if the wording on this principle is too restrictive:
i.e.
_"Do not introduce proprietary concepts in public APIs - FHIR APIs MUST NOT introduce data representations for the sole benefit of parties integrating commercial / proprietary data, where such items would have no discernible benefit for ALL New Zealand health applications that could consume the API."_
The FHIR API models specifically include extension structures that implementors can use to describe their own "commercial / proprietary data", which client applications can use or ignore depending on their use cases and without risk of negatively impacting those applications that are not interested in it. It is a reasonably common use case for an FHIR implementor to need to include their own identifier for a resource (e.g. proprietary identifier for a HealthcareService) which might be of interest to some clients, but probably not of any benefit for ALL New Zealand health applications.
If the intent here is to restrict implementors from changing the standard FHIR API models, then the I agree the principle is important. But it’s not clear if this principle applies for FHIR extensions, which I would argue is a valid way for implementors to provide commercial / proprietary data that might be useful to only some (not ALL) New Zealand health applications.

### Link to standards item

https://apistandards.digital.health.nz/fhir-api-standard/Principles%20and%20Guidelines/Principles

### Which area of the standards does this apply to?

- [ ] Part A - API Concepts
- [ ] Part B - API Security
- [ ] Part C - API Design and Development
- [X] Part D - FHIR
- [ ] Community guidelines

**Comment by swithinfoote** [comment]
Hi @cflemeister , thanks for this detailed feedback. You raise a valid point re FHIR extensions and the relevance to this particular statement. We will have a look at this. Cheers.

**Comment by swithinfoote** [comment]
Hi @cflemeister - we have included a change in the upcoming version 1.2 which should resolve this issue. Cheers.

**Comment by cflemeister** [comment]
Thanks @swithinfoote  -  I see your extra sentence there which accounts for Extensions. 

So I'm happy for this to be closed if this is published in next revision.
