### ISSUE TITLE
[FEEDBACK] - Transaction Concepts don't appear to be consistent with industry practice

### ISSUE THREAD

**Issue by ChrisSquats** [tewhatuora/api-standards#126]
### Summary

Concepts of Bulk, Transaction and Batch are introduced on this page: https://apistandards.digital.health.nz/api-development/Transactions

The following definitions are more aligned with industry practice:
Bulk API - An API that supports multiple sub-requests (i.e. one or more operations on one or more resources) within one client-initiated API invocation.

Transaction API - A type of Bulk API in which the sub-requests are treated as a single transaction. In the event of a failure of a sub-request, it is typical for all sub-requests to be rolled back to preserve atomicity of the transaction.

Batch API - A type of Bulk API in which sub-requests are treats as a collection of operations without dependency on any other sub-request in the request. As such, in the event of a failure with one sub-request, it is typical to continue processing other sub-requests.

Good reference: https://medium.com/cyberark-engineering/how-and-why-to-build-killer-bulk-apis-part-acbbe78f3404

### Link to standards item

https://apistandards.digital.health.nz/api-development/Transactions

### Which area of the standards does this apply to?

- [ ] Part A - API Concepts
- [ ] Part B - API Security
- [X] Part C - API Design and Development
- [ ] Part D - FHIR
- [ ] Community guidelines

**Comment by kyle-mwnz** [comment]
Hi @ChrisSquats - I will close this issue as the feedback has been addressed and is available for review on the 'Draft' version of the standards, to be incorporated into the next official release
