### ISSUE TITLE
[FEEDBACK] Remove the PKCE Mandate on Non-Public Clients

### ISSUE THREAD

**Issue by mathusmith** [tewhatuora/api-standards#132]
Change the use of PKCE for non-public clients to SHOULD instead of MUST.

### Discussed in https://github.com/tewhatuora/api-standards/discussions/70

<div type='discussions-op-text'>

<sup>Originally posted by **felix-tewhatuora** February  2, 2024</sup>
### Summary

Affected page: https://apistandards.digital.health.nz/api-security/SecuringAPIswithOAuth2andOpenIDConnect

PKCE is mandated on all Authorisation code flows for all clients. I fail to see the security benefit of using PKCE for non-public clients (e.g. clients that are not mobile app/desktop application/SPA). Is there a reason it MUST be used for all Authorisation code flows?

It is strongly recommended to briefly outline the advantage of PKCE, why we need it, and when to use it (when the authz code cannot be safely stored, SPA/mobile apps/desktop apps, etc.) . 

Happy to be challenged.

Cheers,
Felix

### Link to standards item

https://apistandards.digital.health.nz/api-security/SecuringAPIswithOAuth2andOpenIDConnect

### Which area of the standards does this apply to?

- [ ] Part A - API Concepts
- [X] Part B - API Security
- [ ] Part C - API Design and Development
- [ ] Part D - FHIR
- [ ] Community guidelines</div>

**Comment by charllanghout01** [comment]
Following on from Felix comment, PKCE is not absolutely necessary and was designed as a protection for public clients. Cloud we clarify "non-public clients"? (is that clients that can securely store secrets, such as web servers or server-side applications?)

While PKCE was designed for public clients, its benefits extend to non-public clients as well, enhancing overall security and aligning with future standards. Therefore, it is recommended to mandate PKCE for all authorization code flows to ensure robust security practices.

**Comment by charllanghout01** [comment]
@ChrisSquats , please see my previous comment and let me know if there is someone else how also need to review?

**Comment by ChrisSquats** [comment]
As per [OAuth2.1 draft](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-10), all clients (confidential and public) are required to support PKCE except:

> unless both of the following criteria are met:
The client is a confidential client.
In the specific deployment and the specific request, there is reasonable assurance by the authorization server that the client implements the OpenID Connect nonce mechanism properly.

Even if these conditions are met, the use of PCKE is still Recommended. As such we're taking the approach to have this as a **MUST** standard.

As such, no change to current standards.
