### ISSUE TITLE
[FEEDBACK] - AsyncAPI specification version

### ISSUE THREAD

**Issue by mathusmith** [tewhatuora/api-standards#134]
### Summary

Change the AsyncAPI version to 2.5 and above, i.e. ... 
Version **2.5** and above of the AsyncAPI specification SHOULD be used when using this standard.

### Link to standards item

https://apistandards.digital.health.nz/draft/api-development/Asynchronous%20APIs/APIDesignandDocumentation/#asyncapi

### Which area of the standards does this apply to?

- [ ] Part A - API Concepts
- [ ] Part B - API Security
- [X] Part C - API Design and Development
- [ ] Part D - FHIR
- [ ] Community guidelines

**Comment by kyle-mwnz** [comment]
Hi @mathusmith, this feedback has incorporated into the Draft version of the standards - thanks
