### ISSUE TITLE
[FEEDBACK] - AsyncAPI version in message body

### ISSUE THREAD

**Issue by mathusmith** [tewhatuora/api-standards#135]
### Summary

It is stated that the version of an AsyncAPI event MUST also to be indicated the message body. The contention is that the version of the event should be allowed to be in the header instead of the body. I.e. ...
"version MUST also be indicated in the message body or header.

### Link to standards item

https://apistandards.digital.health.nz/draft/api-development/Asynchronous%20APIs/TopicDesign#topic-design

### Which area of the standards does this apply to?

- [ ] Part A - API Concepts
- [ ] Part B - API Security
- [X] Part C - API Design and Development
- [ ] Part D - FHIR
- [ ] Community guidelines

**Comment by kyle-mwnz** [comment]
Hi @mathusmith, this feedback has incorporated into the Draft version of the standards - thanks

**Comment by mathusmith** [comment]
All good thanks.
