### ISSUE TITLE
[FEEDBACK] - AsyncAPI - Message Type clarifications

### ISSUE THREAD

**Issue by mathusmith** [tewhatuora/api-standards#137]
### Summary

Consider the following numbered suggestions to improve clarity.
Event Notification
1. > ~~as usually~~ it will contain no data or the minimal amount of data required to inform a consumer ...
2. > This message type SHOULD be used by default and especially when loose coupling between producer and receiver applications is important. ~~if the API Provider does not have full control or knowledge of the event data being sent.~~

Event-Carried State Transfer

3. > These event types typically contain ~~ALL the~~ SUFFICIENT current event/domain data necessary to act upon the event _without the need to contact the source system_, hence the colloquial name "thick events". As they carry the state at a specific point in time they are called "fact events".
4. When should this event message type be used?

Delta Event 
5. This message type needs more explanation - emphasis on delta vs fact message e.g. _A delta event details the changes between one state and another. The contents of a delta event typically includes information about the fields that have changed, the new values for those fields, and may also include the reason for the change. Delta events do not include information about data that hasn’t changed._
6. When should this message type be used?  

- Q: Is relevent to mention the Domain Event type for healthcare - there is a strong case for 'business important' / 'domain significant' events (overlap with rather than distinct from thin events).

FHIR Subscription
Good coverage - no revisions. Just a point of clarification, the FHIR subscription/bundle resource is wholly contained in the message payload allowing for for standard message headers, is that correct?

Message Headers

7. The table "Suggested headers" should be "Suggested header fields" 
- Is appropriate to provide more specific guidelines on required/recommended attributes in the header?
- Should the CloudEvents specification be referenced here in relation to (additional) header fields? 

### Link to standards item

https://apistandards.digital.health.nz/draft/api-development/Asynchronous%20APIs/MessageTypes

### Which area of the standards does this apply to?

- [ ] Part A - API Concepts
- [ ] Part B - API Security
- [X] Part C - API Design and Development
- [ ] Part D - FHIR
- [ ] Community guidelines

**Comment by kyle-mwnz** [comment]
Afternoon @mathusmith,

> Just a point of clarification, the FHIR subscription/bundle resource is wholly contained in the message payload allowing for for standard message headers, is that correct?

Yes, this is correct. In regards to headers the FHIR Subscriptions framework also supports the use of [ R4 - Subscription.channel.header ](https://www.hl7.org/fhir/r4/subscription-definitions.html#Subscription.channel.header) or [R5 - Subscription.parameter ](https://hl7.org/fhir/subscription-definitions.html#Subscription.parameter) to cater for Subscription level defined headers. FHIR describes the intended use as "Channel-dependent information to send as part of the notification" - for example, HTTP headers in a rest-hook channel delivery, or, as part of the message header when using a custom message queue channel - so these would be expected as a message header,outside of the FHIR Bundle contained within the payload.

We will further review the other feedback in this ticket and look at some updates - thank you

**Comment by mathusmith** [comment]
Agree with revision for #2 ... "This message type SHOULD be used if the API Consumer/s may not be fully trusted or if re-authentication of the client is mandatory, which is common when using the Pub/Sub Pattern." 
Happy with the other revisions in response to points raised in the issue.
