### ISSUE TITLE
Flipside of "Realtime Communication"

### ISSUE THREAD

**Issue by spud023** [tewhatuora/api-standards#139]
### Summary

The first listed benefit of Asynchronous APIs and the event-driven paradigm is "Realtime communication". This _is_ a benefit, but the paradigm has historically also been used to facilitate "As soon as possible" communication, for event notification receiving systems that are not always online. Even in today's hyper-connected world, there is still systems downtime due to failures in networks, scheduled maintenance, and so forth. So people who work in the "Realtime Systems" world would be working with non-conventional, highly redundant, very high speed and co-located systems to achieve "realtime" (meaning, in that context, some upper bound of milliseconds for propagation of information, for example, to control an aeroplane's flight systems, or a factory floor machine which must receive signals in time to precisely control a cutting edge, or whatever). 

Perhaps this benefit could be rephrased as "Near Realtime" or "As soon as possible", or something, and include the sub-benefit that the paradigm includes re-try mechanisms to ensure eventual delivery if the event consumer is uncontactable for reasons of failure in the communications substrate, or scheduled downtime. [with a forward reference to where I assume there is a later section on delivery re-try, and levels of guarantee of delivery, which I am yet to read.]

### Link to standards item

https://apistandards.digital.health.nz/draft/api-development/Asynchronous%20APIs/Introduction

### Which area of the standards does this apply to?

- [ ] Part A - API Concepts
- [ ] Part B - API Security
- [X] Part C - API Design and Development
- [ ] Part D - FHIR
- [ ] Community guidelines

**Comment by spud023** [comment]
Dear Editors - I have made some lengthy critiques of the opening paragraphs of "Asynchronous APIs" in issues 139-141 (I think).... But I realise that I have not yet read through the rest of the content in brief yet(as requested by David Moon's intro email) to be able to provide feedback in context.... If you'd like to suspend your reactions to these issues for a few days, I'll try and read through the rest of the actual content, and revise my critique in view of what may be said in the detailed sub-sections of this topic. It may also allow me to make more constructive suggestions about how to edit the introduction.

Best regards,
Keith

**Comment by kyle-mwnz** [comment]
Hi @spud023 - thank you for the feedback across issues #138 to #142. As you suggested, we are happy to wait to receive the feedback in it's entirety, once ready.

Thanks

**Comment by spud023** [comment]
Thanks @kyle-mwnz , I've been in touch with David and Chris by email, and managed to dismiss most of my concerns by actually reading on to the details. Sorry for dumping large, mostly irrelevant commentary... I have written comments on them say what can be ignored, and trying to briefly explain what small parts may still be relevant.

In the case of the Realtime stuff above... I still have concerns about the terminology, but I note that where appropriate in the following text "near-real-time" is used where appropriate, so this is probably not a big deal.

Also, maybe it's just poor reading on my part, but the list of possible benefits of Asych should be clearly labelled as being distinct and separate and not necessarily all achievable in the same system design.

cheers,
|<
