### ISSUE TITLE
Clarity of function, and separation of concerns is needed in the introduction

### ISSUE THREAD

**Issue by spud023** [tewhatuora/api-standards#141]
### Summary

Sorry, I'm taking apart this intro para by para, as, especially in an introduction, it is important to be very clear about what concept means what, and not make assumptions or blur distinctions. This para needs an overhaul IMO:

> Synchronous APIs typically return or generate data when it is requested by a client, however Asynchronous APIs generate or receive data when the data changes, or an event has taken place. This means that the interactions in an Asynchronous API moves from the single client and single server relationship in synchronous APIs where the client initiates the request, to the API Provider publishing events which one or many API Consumers may consume.

An API is an "Interface" to a system, not the whole system that is behind the interface, especially given that they are sometimes facades to offer a single Interface for Inquiry/Action for information compiled from legacy systems, or several backend systems.... especially when FHIR is brought into the picture. So the phrase "Synchronous APIs typically return or generate data" is misleading. The API does "return" data, but it does not "generate" things. An API receives requests to the system(s) behind the interface to perform some actions (including query, generate, update, consume and store, and many other possible actions). In a lot of health information systems, there is a promise/contract by the API to perform a transaction (maybe even an ACID transaction to it's SQL database) behind the scenes, and only to return a positive result once that transaction is successfully completed, otherwise return an error. Others may only promise to accept a piece of data or action request, and process it later, and return a successful invocation result immediately after it has safely recorded the data or action request. This is the most basic distinction (in the application layer with reliable middleware/protocols) between Synchronous and Asynchronous. The latter style may be considered Asynchronous, as the caller does not wait for confirmation of action, but must usually at least be given a confirmation that the request was successfully received. (again I think we're talking about HTTP/TCP/IP here, or a middleware protocol stack that guarantees eventual delivery, not a give-it-your-best shot stack like UDP). 

In a health information system (especially one recording patient data, or requesting a device to be actuated) this kind of Asynchronous API contract is typically insufficiently robust, unless there is a callback, or later polling-based confirmation of a successful data integration or action performance at a later stage. 

The second sentence of the paragraph is also not correct. Publish/Subscribe is the paradigm for multiple recipients of data to be called once an event happens... Asynchronous just means that the API call is non-blocking, and by definition an API call is from 1 client to 1 server (where "client" and "server" are their roles in the API interaction, not necessarily in the Application Architecture. In fact in the Pub/Sub paradigm the Application role of the Publisher is typically that of the "(Data) Server" in the Application Architecture). Again, I think a discussion of which protocol layer you're describing, and the use of the concept of Roles in both API interactions, and application interactions is needed. Here are some concepts that need clarification:

> An API invocation is always from an API's client to its server. An API to register a request for changes to data or other events (a "subscription") is usually from a data consumer (application client) to a data repository (application server), and an API invocation from the data repository (the API client, and Application Server) to the Subscriber for updates (the API server, and usually Application client in this case) reverses the roles for the purpose of API interactions, even though the data repository may be thought of as the "server" in the application architecture. Also, sometimes synchronising data between two peer data repositories will involve each repository acting as both client and server in different API interactions, depending on which one initiates the data synchronisation update.

### Link to standards item

https://apistandards.digital.health.nz/draft/api-development/Asynchronous%20APIs/Introduction#what-is-an-asynchronous-api

### Which area of the standards does this apply to?

- [ ] Part A - API Concepts
- [ ] Part B - API Security
- [X] Part C - API Design and Development
- [ ] Part D - FHIR
- [ ] Community guidelines

**Comment by spud023** [comment]
Again, after looking at the full contents, I see that my questions and comments are dealt with in the main body of the text.  The only things I'd keep would be a caution to not use "API" synonymously with "System + API". And I'd also be wary of "client/server" and "API Provider/API Consumer" designations when moving from 1-client/1-server Synchronous APIs, as stated at length. This is because with some of the patterns you describe have multiple entities, and each entity in the patter may provide one or more APIs, and acts a "server/Provider" in some interactions, and a "client/Consumer" in others. And because these multi-entity patterns are not prefigured before this text, it can be confusing when the previous Synchronous API section has nice clean client/Consumer and server/Provider roles due to its lack of complexity. 

Perhaps a sentence is needed that removes preconceptions of Provider/Consumer and client/server, and a forward reference to the Patterns section, explaining that many entities may be interacting in different roles, in different orders and directions that makes the binary Provider/Consumer client/server not so useful unless looking at a single interaction in a Pattern? Or looking at a higher level view that treats the transmission of data/information from a "Provider"  to one or more "Consumers" as a black box at the application level. Hence I find composite terms "Provider API" and "Consumer API" confusing in the Asych context.

**Comment by kyle-mwnz** [comment]
I will close this issue, as I believe the feedback has also been captured as part of the intro suggestions captured in https://github.com/tewhatuora/api-standards/issues/142#issuecomment-2065709343. If that is not correct, let me know, thanks
