### ISSUE TITLE
Suggest wording change on Concept page

### ISSUE THREAD

**Issue by Skerruish** [tewhatuora/api-standards#146]
### Summary

On the API Concepts page it says 'Welcome to our API Design and Development Standards. This is also included in the 'Introduction' page (under API Concepts).  This is very confusing as Part A is API Concepts and Part C is API Design and Development Standards. You may want to review this and make a change to the first sentence in each of these pages.

### Link to standards item

https://apistandards.digital.health.nz/api-concepts/

### Which area of the standards does this apply to?

- [X] Part A - API Concepts
- [ ] Part B - API Security
- [ ] Part C - API Design and Development
- [ ] Part D - FHIR
- [ ] Community guidelines

**Comment by kyle-mwnz** [comment]
Hi @Skerruish, thank for you raising this - we will take a look
