### ISSUE TITLE
Standard PATH Structure for backend servers

### ISSUE THREAD

**Issue by pat-ryan-health** [tewhatuora/api-standards#148]
### Summary

It would be helpful to have a standard way to construct the backend server api path. This has to be configured on the API GW so it knows where to send the message. Currently https://apistandards.digital.health.nz/api-development/URIs/ has guidance but does not actually state what the standard template should be.

Currently HIP uses this
template
 `/{version}/{namespace}/{version}{resource}/{resource-id}`
example
https://api.hip.digital.health.nz/fhir/nhi/v1/Patient/NHI1234
 
which is compliant with the MoH standard in effect at the time the API was created

### Drawbacks

no drawbacks identified.

### Which area of the standards does this apply to?

- [ ] Part A - API Concepts
- [ ] Part B - API Security
- [X] Part C - API Design and Development
- [ ] Part D - FHIR
- [ ] Community guidelines

**Comment by kyle-mwnz** [comment]
Hi @pat-ryan-health thanks for raising the suggestion - we will take a look

**Comment by mathusmith** [comment]
There is a question as to whether the path needs to identify if an API is FHIR (and what FHIR version). My take is it does not unless there is FHIR and non-FHIR version of the API. The API spec/FHIR IG should inform on this, similarly the API version can cover API versions based on different FHIR versions.

**Comment by pat-ryan-health** [comment]
HIP has SOAP/FHIR and HL7v2  API for patient, so it is useful to be able to disnguish that in the namespace,

Also I think the version number is better placed after the resources since different resources change at different rates, so it is the resource which needs to be able to suppor tapth-based version rather than the product space

**Comment by pat-ryan-health** [comment]
Not sure about this
"
2
protocol version
Must be provided if protocol|standard is provided and relevant
"

If we switched FHIR versions I would only want to change the endpoint if the new  API was not backwards compatible with the old one. Everything the client needs to know about FHIR dependencies should be in the conformance artifacts, I don't see why we need to encode it in the URL. So I would drop that and add guidance on the

4
version
0..1

too say it should be used to differentiate between non-compatible versions of the API

**Comment by ChrisSquats** [comment]
@pat-ryan-health I think this addresses your concerns. Below I've dropped protocol to SHOULD. Also, the guidance for version number is covered under https://apistandards.digital.health.nz/draft/api-development/Synchronous%20APIs/Version%20Control#uri-path-versioning-supported

| Level | Name | Cardinality|
|--------|--------|--------|
| 1 |`protocol\|standard` | 0..1 MUST if the implementation is a FHIR API |
| 2 | `protocol version` | 0..1 SHOULD be provided if protocol\|standard is provided and relevant |
| 3 | `namespace` | 0..1 SHOULD be provided |
| 4 | `version` | 0..1 MAY be provided |
| 5 | `resource`| 1..1 MUST be provided |
| 6 | `resource-id` | 0..1 MUST be provided when interacting with a Resource Instance |
| 7 | `sub-resource` | 0..1 MUST be provided when interacting with a Sub-resource |
| 8 | `sub-resource-id`| 0..1 MUST be provided when interacting with a Sub-resource instance |
