### ISSUE TITLE
SMART scopes for custom operations

### ISSUE THREAD

**Issue by pat-ryan-health** [tewhatuora/api-standards#154]
### Summary

Use a "__" prefix before the custom operation name  when it is necessary to assign a specific scope to a custom operation

From 
[SMART](https://build.fhir.org/ig/HL7/smart-app-launch/scopes-and-launch-context.html#example-extra-scopes---extensions-for-non-fhir-apis)

_“If a SMART on FHIR server supports a custom behavior like allowing users to choose their own profile photos through a custom non-FHIR API, it can designate a custom scope using a full URL (e.g., https://ehr.example.org/scopes/profilePhoto.manage) or by using a "__" prefix (e.g., __profilePhoto.manage)”_

example - if we wanted to assign a specific scope to permit access to the NHIPatient custom operation `set-preferred-name`

we could define a scope called `Patient.__set-preferred-name`

### Drawbacks

none identified

### Which area of the standards does this apply to?

- [ ] Part A - API Concepts
- [X] Part B - API Security
- [ ] Part C - API Design and Development
- [ ] Part D - FHIR
- [ ] Community guidelines

**Comment by ChrisSquats** [comment]
I've actually raised [this](https://chat.fhir.org/#narrow/stream/179170-smart/topic/Using.20SMART.20scopes.20for.20authorizing.20Operations/near/435600050) in the FHIR community chat. This was the recommendation:
![image](https://github.com/tewhatuora/api-standards/assets/153867719/ab91b450-f493-40b5-a0e7-caf09fc72bcb)
As such, I'll add this to the standard.
