### ISSUE TITLE
[FEEDBACK] - Capability Statement

### ISSUE THREAD

**Issue by pat-ryan-health** [tewhatuora/api-standards#157]
### Summary

I thgink it is useful if the API page includes which FHIR scoeps are required to access the operation/interactrion

e.g

https://mws-ig.hip.digital.health.nz/API.html

### Link to standards item

https://apistandards.digital.health.nz/draft/api-publishing/implementation-guides#fhir-artifacts

### Which area of the standards does this apply to?

- [ ] Part A - API Concepts
- [ ] Part B - API Security
- [ ] Part C - API Design and Development
- [X] Part D - FHIR
- [ ] Community guidelines

**Comment by swithinfoote** [comment]
Hi @pat-ryan-health - a change has been included in the upcoming v1.2 release that includes the definition of authorisation scopes in the CapabilityStatement. Cheers.
