### ISSUE TITLE
[API Standards] - Incomplete sentence

### ISSUE THREAD

**Issue by andyhnz** [tewhatuora/api-standards#160]
### Summary

There is a sentence that does seem to be complete under Developer onboarding "API consumer application developers"

### Link to standards item

https://apistandards.digital.health.nz/draft/api-publishing/Components

### Which area of the standards does this apply to?

- [ ] Part A - API Concepts
- [ ] Part B - API Security
- [ ] Part C - API Design and Development
- [X] Part D - FHIR
- [ ] Community guidelines

**Comment by swithinfoote** [comment]
Thanks for picking this up @andyhnz - a PR has been raised to rectify.
Cheers.
