### ISSUE TITLE
[FEEDBACK] - Nationwide FHIR Mappings

### ISSUE THREAD

**Issue by f3derical** [tewhatuora/api-standards#161]
### Summary

Hi there, I am questioning the need for each FHIR API designer to provide the mapping for each business domain. 
There is a variety of origin data (HL7v2 segments, HL7v3, CCDA sections, ...) that will be mapped to specific FHIR resources. Should it not be the responsibility of Te Whatu Ora to provide the expected mappings at a national level instead? 

### Link to standards item

https://apistandards.digital.health.nz/draft/fhir-api-standard/Principles%20and%20Guidelines/DataMapping

### Which area of the standards does this apply to?

- [ ] Part A - API Concepts
- [ ] Part B - API Security
- [ ] Part C - API Design and Development
- [X] Part D - FHIR
- [ ] Community guidelines

**Comment by daniel-thomson** [comment]
Hi @f3derical 

I think the linked section is attempting to provide general guidance on best practice for design of a FHIR API if you're developing an API for a new use case - to make sure the mapping from data sources (that HNZ might have no view of to provide a mapping) is clear to stakeholders. 

You're correct that it would be good to standardise on the interfaces for sharing of data for various scenarios (and this might include mappings from existing systems / standards where that's possible) - that's beyond the scope of this section of the standard for now, and more in the realm of things like NZBase, HISO standards, a potential future NZ Core standard, etc.
