### ISSUE TITLE
[FEEDBACK] - Who defines SLAs

### ISSUE THREAD

**Issue by f3derical** [tewhatuora/api-standards#163]
### Summary

I would argue that the SLA is dependent on a number of factors, first and foremost the storage piece as well as perhaps the API gateway. Is the SLA definition responsibility of the API designer only?

### Link to standards item

https://apistandards.digital.health.nz/fhir-api-standard/Standards/APIDeliverables#fhir-apis-must-deliver-the-following-items

### Which area of the standards does this apply to?

- [ ] Part A - API Concepts
- [ ] Part B - API Security
- [X] Part C - API Design and Development
- [ ] Part D - FHIR
- [ ] Community guidelines

**Comment by davidmoonTWO** [comment]
Hi - where an API being developed, the definition to the SLA will be with the API owner/developer to determine, define and adhere to to ensure consumers of the API understand this when they consume it. I would expect this to be determined through the design process, and NFRs to the service being developed to what is achievable on numerous factors.

**Comment by nicodewet** [comment]
Agree that SLAs should be defined by whoever produces an API.

But, it is still interesting to think about how one would formally (OpenAPI, AsyncAPI or older standards) document quality attributes. There is the ever-present risk that enforcement is outsourced to intermediary infrastructure (e.g. a Gateway) with no hint of such aspects in the actual specification (one could easily forget to include say [Rate Limit Headers](https://www.developer.saxo/openapi/learn/rate-limiting) in an OpenAPI specification).

PS I'm not suggesting re-opening, this is just a comment.
