### ISSUE TITLE
[FEEDBACK] - Informing consumers

### ISSUE THREAD

**Issue by f3derical** [tewhatuora/api-standards#164]
### Summary

How are consumers informed of new APIs available?

### Link to standards item

https://apistandards.digital.health.nz/fhir-api-standard/Standards/APIDeliverables

### Which area of the standards does this apply to?

- [ ] Part A - API Concepts
- [ ] Part B - API Security
- [X] Part C - API Design and Development
- [ ] Part D - FHIR
- [ ] Community guidelines

**Comment by davidmoonTWO** [comment]
All new APIs should be published and notified via the Digital Services Hub - this is now live from early adopters. New services relating to API availability will be published here: _Available from 20th June_
